Repository snapshot-labs/snapshot-strategies, pull requests merged in 2021-08, with the labels that each got.

#3 [cake] feat(cake): Minimum voting power
  src/strategies/cake/index.ts
Labels: strategy

#5 [anti-whale] Add anti-whale strategy
  src/strategies/anti-whale/README.md
  src/strategies/anti-whale/examples.json
  src/strategies/anti-whale/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#13 [biswap] Add biswap strategy
  src/strategies/biswap/README.md
  src/strategies/biswap/examples.json
  src/strategies/biswap/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#11 [l2-deversifi] L2-deversifi strategy
  src/strategies/index.ts
  src/strategies/l2-deversifi/examples.json
  src/strategies/l2-deversifi/index.ts
Labels: strategy, ready to merge

#4 [uniswap-v3] Add Pilot Protocol
  package-lock.json
  package.json
  src/strategies/index.ts
  src/strategies/uniswap-v3/examples.json
  src/strategies/uniswap-v3/helper.ts
  src/strategies/uniswap-v3/index.ts
Labels: strategy, ready to merge

#17 [vested-deversifi] Strategy for allowing those with vested deversifi tokens on-chain to vote
  src/strategies/index.ts
  src/strategies/vested-deversifi/examples.json
  src/strategies/vested-deversifi/index.ts
Labels: strategy, ready to merge

#22 [erc721-multi-registry] add multiple ERC721 registry strategy
  src/strategies/erc721-multi-registry/README.md
  src/strategies/erc721-multi-registry/examples.json
  src/strategies/erc721-multi-registry/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#19 [delegation] Fix delegation strategy score calculation issue
  src/strategies/delegation/index.ts
Labels: strategy, ready to merge

#23 Lint fix
  src/strategies/balance-of-with-thresholds/index.ts
  src/strategies/biswap/index.ts
  src/strategies/cake/index.ts
  src/strategies/erc721-with-tokenid/index.ts
  src/strategies/planet-finance/index.ts
  src/strategies/uniswap-v3/helper.ts
  src/strategies/uniswap-v3/index.ts
  src/strategies/vested-deversifi/index.ts
Labels: ready to merge

#20 [sushiswap] Optionally use staked LP tokens
  src/strategies/sushiswap/README.md
  src/strategies/sushiswap/examples.json
  src/strategies/sushiswap/index.ts
Labels: strategy, ready to merge

#26 [uniswap-v3] fix indexOf issue
  src/strategies/uniswap-v3/index.ts
Labels: strategy, ready to merge

#24 [egl-vote] Add the egl vote strategy
  src/strategies/egl-vote/README.md
  src/strategies/egl-vote/examples.json
  src/strategies/egl-vote/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#27 [sunder] Add sunder strategy
  src/strategies/index.ts
  src/strategies/sunder/examples.json
  src/strategies/sunder/index.ts
Labels: strategy, ready to merge

#28 [multichain] fix params in multichain strategy example to include token name
  src/strategies/multichain/examples.json
Labels: strategy, ready to merge

#25 [honeyswap] Added Honeyswap strategy
  src/strategies/honeyswap/README.md
  src/strategies/honeyswap/examples.json
  src/strategies/honeyswap/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#29 [poap-with-weight] Poap with weight
  src/strategies/index.ts
  src/strategies/poap-with-weight/README.md
  src/strategies/poap-with-weight/examples.json
  src/strategies/poap-with-weight/index.ts
Labels: strategy, ready to merge

#30 [balancer-erc20-internal-balance-of] add vault internal balances strategy
  src/strategies/balancer-erc20-internal-balance-of/README.md
  src/strategies/balancer-erc20-internal-balance-of/examples.json
  src/strategies/balancer-erc20-internal-balance-of/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#33 [crucible-erc20-balance-of] add crucible erc20 balanceOf strategy
  src/strategies/crucible-erc20-balance-of/README.md
  src/strategies/crucible-erc20-balance-of/examples.json
  src/strategies/crucible-erc20-balance-of/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#35 [erc721-multi-registry] fix erc721-multi-strategy parameters
  src/strategies/erc721-multi-registry/README.md
  src/strategies/erc721-multi-registry/examples.json
  src/strategies/erc721-multi-registry/index.ts
Labels: strategy

#34 [meebitsdao] Add meebitsdao strategy
  src/strategies/index.ts
  src/strategies/meebitsdao/README.md
  src/strategies/meebitsdao/examples.json
  src/strategies/meebitsdao/index.ts
Labels: strategy, changes requested, not scalable

#41 Update networks.json
  src/networks.json
Labels: ready to merge

#38 [snowswap] add snowswap balanceOf strategy
  src/strategies/index.ts
  src/strategies/snowswap/README.md
  src/strategies/snowswap/examples.json
  src/strategies/snowswap/index.ts
Labels: strategy, ready to merge

#39 [crucible-erc20-balance-of] Add symbol in example params
  src/strategies/crucible-erc20-balance-of/examples.json
Labels: strategy, ready to merge

#31 [mcn-farm] Add mcn-farm strategy
  src/strategies/index.ts
  src/strategies/mcn-farm/README.md
  src/strategies/mcn-farm/examples.json
  src/strategies/mcn-farm/index.ts
Labels: strategy, ready to merge

#46 [has-rock] Rock NFT voting strategy
  src/strategies/has-rock/README.md
  src/strategies/has-rock/examples.json
  src/strategies/has-rock/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#44 Replace duplicate code with snapshot.js
  package-lock.json
  package.json
  src/gateways.json
  src/networks.json
  src/strategies/aavegotchi-agip/index.ts
  src/strategies/balancer-erc20-internal-balance-of/index.ts
  src/strategies/biswap/index.ts
  src/strategies/cream/index.ts
  src/strategies/crucible-erc20-balance-of/index.ts
  src/strategies/dittomoney/index.ts
  src/strategies/egl-vote/index.ts
  src/strategies/erc20-balance-of/index.ts
  src/strategies/eth-balance/index.ts
  src/strategies/impossible-finance/index.ts
  src/strategies/multichain/index.ts
  src/strategies/mushrooms/index.ts
  src/strategies/ogn/index.ts
  src/strategies/planet-finance/index.ts
  src/strategies/rebased/index.ts
  src/strategies/rnbw-balance/index.ts
  src/strategies/snowswap/index.ts
  src/strategies/spookyswap/index.ts
  src/strategies/stablexswap/index.ts
  src/strategies/sunder/index.ts
  src/strategies/tomb-finance/index.ts
  src/strategies/typhoon/index.ts
  src/strategies/work/index.ts
  src/utils.ts
  src/utils/delegation.ts
  src/utils/multicaller.ts
  src/utils/provider.ts
  src/utils/web3.ts
  test/ERC20.json
  test/index.spec.ts
  test/scores.ts
Labels: ready to merge

#52 Snapshot.js update to latest version
  package-lock.json
  package.json
Labels: ready to merge

#49 [dfyn-staked-in-vaults] dfyn-staked-in-vaults strategy added
  src/strategies/dfyn-staked-in-vaults/README.md
  src/strategies/dfyn-staked-in-vaults/examples.json
  src/strategies/dfyn-staked-in-vaults/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#50 [infinityprotocol-liquidity-pools] changes in infinityprotocol-liquidity-pools strategy
  src/strategies/infinityprotocol-liquidity-pools/README.md
  src/strategies/infinityprotocol-liquidity-pools/examples.json
  src/strategies/infinityprotocol-liquidity-pools/index.ts
Labels: strategy, ready to merge

#48 [dfyn-staked-in-farms] dfyn-staked-in-farms strategy added
  src/strategies/dfyn-staked-in-farms/README.md
  src/strategies/dfyn-staked-in-farms/examples.json
  src/strategies/dfyn-staked-in-farms/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge
