Repository snapshot-labs/snapshot-strategies, pull requests merged in 2021-09, with the labels that each got.

#53 [dfyn-staked-in-vaults] Update dfyn-staked-in-vaults index.ts
  src/strategies/dfyn-staked-in-vaults/index.ts
Labels: strategy, ready to merge

#55 [crucible-erc20-balance-of] Update - Edge Case Resolution - Padding Addresses
  src/strategies/crucible-erc20-balance-of/examples.json
  src/strategies/crucible-erc20-balance-of/index.ts
Labels: strategy, ready to merge

#57 [faraland-staking] add fara staking strategy
  src/strategies/faraland-staking/examples.json
  src/strategies/faraland-staking/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#59 [dextf-staked-in-vaults] DEXTF: staked tokens
  src/strategies/dextf-staked-in-vaults/README.md
  src/strategies/dextf-staked-in-vaults/examples.json
  src/strategies/dextf-staked-in-vaults/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#62 [sunrisegaming-staking] Add sunrisegaming-staking strategy
  src/strategies/index.ts
  src/strategies/sunrisegaming-staking/README.md
  src/strategies/sunrisegaming-staking/examples.json
  src/strategies/sunrisegaming-staking/index.ts
Labels: strategy, ready to merge

#63 [iotex-balance] change IOTEX server URI
  src/strategies/iotex-balance/examples.json
  src/strategies/iotex-balance/index.ts
  src/strategies/iotex-staked-balance/index.ts
Labels: strategy

#64 [cake]: Fix subgraph URI
  src/strategies/cake/index.ts
Labels: strategy

#65 [sunrisegaming-univ2-lp] Add sunrisegaming-univ2-lp strategy
  src/strategies/index.ts
  src/strategies/sunrisegaming-univ2-lp/README.md
  src/strategies/sunrisegaming-univ2-lp/examples.json
  src/strategies/sunrisegaming-univ2-lp/index.ts
Labels: strategy

#60 [flexa-capacity-staking] Add Flexa Capacity staking strategy
  src/strategies/flexa-capacity-staking/examples.json
  src/strategies/flexa-capacity-staking/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#67 [synthetix] Update existing strategy with the upcoming election values and create a non-weighted version
  src/strategies/index.ts
  src/strategies/synthetix-non-quadratic/README.md
  src/strategies/synthetix-non-quadratic/examples.json
  src/strategies/synthetix-non-quadratic/index.ts
  src/strategies/synthetix-quadratic/README.md
  src/strategies/synthetix-quadratic/examples.json
  src/strategies/synthetix-quadratic/index.ts
  src/strategies/synthetix/helper.ts
  src/strategies/synthetix/index.ts
Labels: strategy, ready to merge

#68 [single-staking-pools-balanceof] New Strategy for Single Staking Pools
  src/strategies/index.ts
  src/strategies/single-staking-pools-balanceof/README.md
  src/strategies/single-staking-pools-balanceof/examples.json
  src/strategies/single-staking-pools-balanceof/index.ts
Labels: strategy, ready to merge

#69 Update Snapshot.js version and lint fixes
  package-lock.json
  package.json
  src/strategies/coordinape/index.ts
  src/strategies/faraland-staking/index.ts
  src/strategies/has-rock/index.ts
  src/strategies/iotex-staked-balance/index.ts
  src/strategies/sunrisegaming-staking/index.ts
  src/strategies/sunrisegaming-univ2-lp/index.ts
Labels: ready to merge

#70 [balance-in-vdfyn-vault] Added vdfyn strategy
  src/strategies/balance-in-vdfyn-vault/README.md
  src/strategies/balance-in-vdfyn-vault/examples.json
  src/strategies/balance-in-vdfyn-vault/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#75 [hopr-bridged-balance] Hopr bridged balance
  src/strategies/hopr-bridged-balance/examples.json
  src/strategies/hopr-bridged-balance/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#76 [hopr-staking] Hopr staking
  src/strategies/hopr-staking/examples.json
  src/strategies/hopr-staking/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#83 [mcn-farm] Update MCN strategy to handle different reward token positions
  src/strategies/mcn-farm/index.ts
Labels: strategy, ready to merge

#84 [loot-character-guilds] Add a Loot Character Guild Strategy
  src/strategies/index.ts
  src/strategies/loot-character-guilds/examples.json
  src/strategies/loot-character-guilds/index.ts
Labels: strategy, ready to merge
