Repository snapshot-labs/snapshot-strategies, pull requests merged in 2021-11, with the labels that each got.

#129 [the-graph-indexing] The Graph strategies refactor and documentation
  src/strategies/the-graph-balance/README.md
  src/strategies/the-graph-balance/balances.ts
  src/strategies/the-graph-balance/examples.json
  src/strategies/the-graph-balance/index.ts
  src/strategies/the-graph-delegation/README.md
  src/strategies/the-graph-delegation/delegators.ts
  src/strategies/the-graph-delegation/examples.json
  src/strategies/the-graph-delegation/index.ts
  src/strategies/the-graph-indexing/README.md
  src/strategies/the-graph-indexing/examples.json
  src/strategies/the-graph-indexing/index.ts
  src/strategies/the-graph-indexing/indexers.ts
  src/strategies/the-graph/README.md
  src/strategies/the-graph/baseStrategy.ts
  src/strategies/the-graph/graphUtils.ts
  src/strategies/the-graph/tokenLockWallets.ts
Labels: strategy, ready to merge

#135 [digitalax-lp-stakers] Digitalax mainnet LP stakers strategy
  src/strategies/digitalax-lp-stakers/examples.json
  src/strategies/digitalax-lp-stakers/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#136 [digitalax-mona-quickswap] Digitalax mona quickswap
  src/strategies/digitalax-mona-quickswap/README.md
  src/strategies/digitalax-mona-quickswap/examples.json
  src/strategies/digitalax-mona-quickswap/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#138 [galaxy-nft-with-score] add strategy: galaxy-nft-with-score
  src/strategies/galaxy-nft-with-score/examples.json
  src/strategies/galaxy-nft-with-score/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#137 [the-graph-balance] fix: The Graph strategies pagination
  src/strategies/the-graph-balance/balances.ts
  src/strategies/the-graph-balance/index.ts
  src/strategies/the-graph-delegation/delegators.ts
  src/strategies/the-graph-delegation/index.ts
  src/strategies/the-graph-indexing/index.ts
  src/strategies/the-graph-indexing/indexers.ts
  src/strategies/the-graph/baseStrategy.ts
  src/strategies/the-graph/tokenLockWallets.ts
Labels: strategy, ready to merge

#132 [radicle-community-tokens] add strategy: radicle-funding-nft, community tokens
  src/strategies/index.ts
  src/strategies/radicle-community-tokens/README.md
  src/strategies/radicle-community-tokens/examples.json
  src/strategies/radicle-community-tokens/index.ts
Labels: strategy, ready to merge

#143 Fix for [galaxy-nft-with-score], query subgraph with snapshot id.
  src/strategies/galaxy-nft-with-score/examples.json
  src/strategies/galaxy-nft-with-score/index.ts
Labels: strategy, ready to merge

#145 Fix: [galaxy-nft-with-score] strategy variable name fix according to user request.
  src/strategies/galaxy-nft-with-score/examples.json
  src/strategies/galaxy-nft-with-score/index.ts
Labels: strategy

#142 [vesper] Add Vesper strategy
  src/strategies/index.ts
  src/strategies/vesper/examples.json
  src/strategies/vesper/index.ts
Labels: strategy, ready to merge

#86 [swapr] Implement custom strategy for Swapr governance
  src/strategies/index.ts
  src/strategies/swapr/README.md
  src/strategies/swapr/commons.ts
  src/strategies/swapr/examples.json
  src/strategies/swapr/index.ts
  src/strategies/swapr/swapr-lps.ts
Labels: strategy, ready to merge

#147 [aks] AKS strategy
  src/strategies/aks/README.md
  src/strategies/aks/examples.json
  src/strategies/aks/index.ts
  src/strategies/index.ts
Labels: strategy

#150 [balancer] Add support for tracking tokens in Balancer pools on Polygon + Arbitrum
  src/strategies/balancer/index.ts
Labels: strategy, ready to merge

#151 [multichain] feat: add arbitrum support to multichain strategy
  src/strategies/multichain/index.ts
Labels: strategy, ready to merge

#155 [multichain] add optional start block for each network
  src/strategies/multichain/examples.json
  src/strategies/multichain/index.ts
Labels: strategy, ready to merge

#160 [tech-quadratic-ranked-choice] TECH stragegy
  src/strategies/index.ts
  src/strategies/tech-quadratic-ranked-choice/README.md
  src/strategies/tech-quadratic-ranked-choice/examples.json
  src/strategies/tech-quadratic-ranked-choice/index.ts
Labels: strategy, ready to merge

#152 [thales] Thales strategy
  src/strategies/index.ts
  src/strategies/thales/README.md
  src/strategies/thales/examples.json
  src/strategies/thales/index.ts
Labels: strategy, ready to merge

#159 [coinswap] Coinswap
  src/strategies/coinswap/README.md
  src/strategies/coinswap/examples.json
  src/strategies/coinswap/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#164 [governor-delegator] Ens delegator strategy
  src/strategies/governor-delegator/README.md
  src/strategies/governor-delegator/examples.json
  src/strategies/governor-delegator/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#165 [coinswap] snapshot block number validation added
  src/strategies/coinswap/examples.json
  src/strategies/coinswap/index.ts
Labels: strategy

#167 [saffron-finance-v2] Saffron Finance V2 Strategy
  src/strategies/index.ts
  src/strategies/saffron-finance-v2/README.md
  src/strategies/saffron-finance-v2/examples.json
  src/strategies/saffron-finance-v2/index.ts
Labels: strategy, ready to merge

#166 [nouns-rfp-power] Nouns Power Strategy
  src/strategies/index.ts
  src/strategies/nouns-rfp-power/examples.json
  src/strategies/nouns-rfp-power/index.ts
Labels: strategy, ready to merge

#169 [tech-quadratic-ranked-choice] Fix wrong decimal number on return
  src/strategies/tech-quadratic-ranked-choice/index.ts
Labels: strategy

#172 [vote-power-and-share] Vote power and share strategy
  src/strategies/index.ts
  src/strategies/vote-power-and-share/README.md
  src/strategies/vote-power-and-share/examples.json
  src/strategies/vote-power-and-share/index.ts
Labels: strategy, ready to merge

#177 [dgenesis] dGenesis Strategy
  src/strategies/dgenesis/README.md
  src/strategies/dgenesis/examples.json
  src/strategies/dgenesis/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#185 Add symbol where it is missing
  src/strategies/anti-whale/examples.json
  src/strategies/badgeth/examples.json
  src/strategies/curio-cards-erc20-weighted/examples.json
  src/strategies/ens-domains-owned/examples.json
  src/strategies/ens-reverse-record/examples.json
  src/strategies/erc1155-balance-of-cv/examples.json
  src/strategies/erc1155-balance-of/examples.json
  src/strategies/eth-balance/examples.json
  src/strategies/eth-philanthropy/examples.json
  src/strategies/eth-received/examples.json
  src/strategies/eth-wallet-age/examples.json
  src/strategies/eth-with-balance/examples.json
  src/strategies/flexa-capacity-staking/examples.json
  src/strategies/hopr-bridged-balance/examples.json
  src/strategies/hopr-uni-lp-farm/examples.json
  src/strategies/l2-deversifi/examples.json
  src/strategies/loot-character-guilds/examples.json
  src/strategies/masterchef-pool-balance-price/examples.json
  src/strategies/masterchef-pool-balance/examples.json
  src/strategies/moloch-all/examples.json
  src/strategies/moloch-loot/examples.json
  src/strategies/mstable/examples.json
  src/strategies/multisig-owners/examples.json
  src/strategies/ocean-marketplace/examples.json
  src/strategies/opium/examples.json
  src/strategies/piedao/examples.json
  src/strategies/pob-hash/examples.json
  src/strategies/pod-leader/examples.json
  src/strategies/rebased/examples.json
  src/strategies/ren-nodes/examples.json
  src/strategies/single-staking-vault-balanceof/examples.json
  src/strategies/spookyswap/examples.json
  src/strategies/stablexswap/examples.json
  src/strategies/staked-keep/examples.json
  src/strategies/ticket/examples.json
  src/strategies/tomb-finance/examples.json
  src/strategies/total-axion-shares/examples.json
  src/strategies/typhoon/examples.json
  src/strategies/uniswap-v3-staking/examples.json
  src/strategies/uniswap-v3/examples.json
  src/strategies/vested-deversifi/examples.json
  src/strategies/xdai-posdao-staking/examples.json
  src/strategies/xdai-stake-holders/examples.json
  src/strategies/yearn-vault/examples.json
Labels: ready to merge

#176 [tomyumswap] Strategy tomyumswap added
  src/strategies/index.ts
  src/strategies/tomyumswap/README.md
  src/strategies/tomyumswap/examples.json
  src/strategies/tomyumswap/index.ts
Labels: strategy, ready to merge

#182 [push-voting-power] Ethereum Push Notification Service ($PUSH) Governance: Custom strategy for voting
  src/strategies/index.ts
  src/strategies/push-voting-power/README.md
  src/strategies/push-voting-power/examples.json
  src/strategies/push-voting-power/index.ts
Labels: strategy, ready to merge

#186 Automated lint workflow
  .github/workflows/main.yml
Labels: ready to merge

#184 Test author and version in strategy
  test/index.spec.ts
Labels: ready to merge

#181 [blockzerolabs-cryptonauts] Adding Blockzerolabs Cryptonauts Strategy
  src/strategies/blockzerolabs-cryptonauts/README.md
  src/strategies/blockzerolabs-cryptonauts/examples.json
  src/strategies/blockzerolabs-cryptonauts/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#188 Strategy: erc1155 with multiplier [erc1155-with-multiplier]
  src/strategies/erc1155-with-multiplier/examples.json
  src/strategies/erc1155-with-multiplier/index.ts
  src/strategies/index.ts
  test/index.spec.ts
Labels: strategy, ready to merge

#190 [math] Add math strategy
  src/strategies/index.ts
  src/strategies/math/README.md
  src/strategies/math/examples.json
  src/strategies/math/index.ts
Labels: strategy, ready to merge

#191 [staked-psp-balance] ParaSwap::Staked PSP strategy
  src/strategies/index.ts
  src/strategies/staked-psp-balance/README.md
  src/strategies/staked-psp-balance/examples.json
  src/strategies/staked-psp-balance/index.ts
Labels: strategy, ready to merge

#196 [sushiswap] - Add support for the xDai network
  src/strategies/sushiswap/index.ts
Labels: strategy

#195 [agave] - Add strategy
  src/strategies/agave/README.md
  src/strategies/agave/examples.json
  src/strategies/agave/index.ts
  src/strategies/index.ts
Labels: strategy, changes requested

#197 [honeyswap] - Optionally use staked LP tokens
  src/strategies/honeyswap/README.md
  src/strategies/honeyswap/examples.json
  src/strategies/honeyswap/index.ts
Labels: strategy, ready to merge

#198 [erc20-balance-of-contract-multiplier] ERC20 Balance of with contract multiplier strategy
  src/strategies/erc20-balance-of-contract-multiplier/README.md
  src/strategies/erc20-balance-of-contract-multiplier/examples.json
  src/strategies/erc20-balance-of-contract-multiplier/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#200 [sushiswap] Add pagination to subgraph requests
  src/strategies/sushiswap/index.ts
Labels: strategy, ready to merge
