Repository snapshot-labs/snapshot-strategies, pull requests merged in 2021-12, with the labels that each got.

#205 [whitelist-weighted] Add whitelist-weighted strategy
  src/strategies/index.ts
  src/strategies/whitelist-weighted/README.md
  src/strategies/whitelist-weighted/examples.json
  src/strategies/whitelist-weighted/index.ts
Labels: strategy, ready to merge

#202 [snet-liquidity-providers] strategy: snet-liquidity-providers
  src/strategies/index.ts
  src/strategies/snet-liquidity-providers/README.md
  src/strategies/snet-liquidity-providers/examples.json
  src/strategies/snet-liquidity-providers/index.ts
Labels: strategy, ready to merge

#203 [snet-stakers] strategy: snet-stakers
  src/strategies/index.ts
  src/strategies/snet-stakers/README.md
  src/strategies/snet-stakers/examples.json
  src/strategies/snet-stakers/index.ts
Labels: strategy, ready to merge

#204 [snet-farmers] Strategy
  src/strategies/index.ts
  src/strategies/snet-farmers/README.md
  src/strategies/snet-farmers/examples.json
  src/strategies/snet-farmers/index.ts
Labels: strategy, ready to merge

#206 [juicebox] strategy
  src/strategies/index.ts
  src/strategies/juicebox/examples.json
  src/strategies/juicebox/index.ts
Labels: strategy, ready to merge

#211 [biswap] UPDATE: Stategy: biswap
  src/strategies/biswap/examples.json
  src/strategies/biswap/index.ts
Labels: strategy, ready to merge

#223 [aelin-council] Add Aelin Strategy
  src/strategies/aelin-council/README.md
  src/strategies/aelin-council/examples.json
  src/strategies/aelin-council/index.ts
  src/strategies/index.ts
Labels: strategy

#217 Add StackedToadz strategy [unstackedtoadz-and-stackedtoadz-stakers]
  src/strategies/index.ts
  src/strategies/unstackedtoadz-and-stackedtoadz-stakers/README.md
  src/strategies/unstackedtoadz-and-stackedtoadz-stakers/examples.json
  src/strategies/unstackedtoadz-and-stackedtoadz-stakers/index.ts
Labels: strategy, ready to merge

#219 [minmax-mcn-farm] Add custom strategy for minmax finance
  src/strategies/index.ts
  src/strategies/minmax-mcn-farm/README.md
  src/strategies/minmax-mcn-farm/examples.json
  src/strategies/minmax-mcn-farm/index.ts
Labels: strategy, ready to merge

#213 [api] Update index.ts
  src/strategies/api/index.ts
Labels: strategy, ready to merge

#216 [planet-finance] UPDATE_VOTING-STRATEGY
  src/strategies/planet-finance/examples.json
  src/strategies/planet-finance/index.ts
Labels: strategy, ready to merge

#229 fix: update api url [coordinape]
  src/strategies/coordinape/index.ts
Labels: strategy, ready to merge

#230 XKawa-frm strat [xkawa-farm]
  src/strategies/index.ts
  src/strategies/xkawa-farm/README.md
  src/strategies/xkawa-farm/examples.json
  src/strategies/xkawa-farm/index.ts
Labels: strategy, ready to merge

#232 [lydia-gov-vault] Adds Lydia governance vault strategy
  src/strategies/index.ts
  src/strategies/lydia-gov-vault/README.md
  src/strategies/lydia-gov-vault/examples.json
  src/strategies/lydia-gov-vault/index.ts
Labels: strategy, ready to merge

#237 [darkforest-score] dark forest custom scoring
  src/strategies/darkforest-score/README.md
  src/strategies/darkforest-score/examples.json
  src/strategies/darkforest-score/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#214 [saddle-finance] Saddle Finance Strategy
  src/strategies/index.ts
  src/strategies/saddle-finance/README.md
  src/strategies/saddle-finance/examples.json
  src/strategies/saddle-finance/index.ts
  src/strategies/saddle-finance/vestingContractAddrs.ts
Labels: strategy, ready to merge

#241 [biswap] Update Biswap Strategy
  src/strategies/biswap/README.md
  src/strategies/biswap/examples.json
  src/strategies/biswap/index.ts
Labels: strategy

#242 [synthetix-quadratic_1] Clone and update synthetix strategies for upcoming election
  src/strategies/index.ts
  src/strategies/synthetix-non-quadratic_1/README.md
  src/strategies/synthetix-non-quadratic_1/examples.json
  src/strategies/synthetix-non-quadratic_1/index.ts
  src/strategies/synthetix-quadratic_1/README.md
  src/strategies/synthetix-quadratic_1/examples.json
  src/strategies/synthetix-quadratic_1/index.ts
Labels: strategy, ready to merge

#224 [ocean-dao-brightid] Add Ocean DAO BrightID strategy
  src/strategies/index.ts
  src/strategies/ocean-dao-brightid/README.md
  src/strategies/ocean-dao-brightid/examples.json
  src/strategies/ocean-dao-brightid/index.ts
Labels: strategy, ready to merge

#243 [unipool-xsushi] xSushi voting power strategy
  src/strategies/index.ts
  src/strategies/unipool-xsushi/examples.json
  src/strategies/unipool-xsushi/index.ts
Labels: ready to merge

#244 [synthetix-quadratic_1]make params dynamic
  src/strategies/synthetix-non-quadratic_1/examples.json
  src/strategies/synthetix-non-quadratic_1/index.ts
  src/strategies/synthetix-quadratic_1/examples.json
  src/strategies/synthetix-quadratic_1/index.ts
Labels: strategy, ready to merge

#226 Feat: jade-smrt strat [jade-smrt]
  src/strategies/index.ts
  src/strategies/jade-smrt/README.md
  src/strategies/jade-smrt/examples.json
  src/strategies/jade-smrt/index.ts
Labels: strategy, ready to merge

#248 [masterchef-pool-balance] Update to masterchef-pool-balance
  src/strategies/masterchef-pool-balance/examples.json
  src/strategies/masterchef-pool-balance/index.ts
Labels: strategy, ready to merge

#246 [botto-dao] Adds Botto DAO governance strategy
  src/strategies/botto-dao/README.md
  src/strategies/botto-dao/examples.json
  src/strategies/botto-dao/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#221 [math] Add min and max operations to `math` strategy
  src/strategies/math/README.md
  src/strategies/math/examples.json
  src/strategies/math/index.ts
  src/strategies/math/options.ts
Labels: strategy, ready to merge

#249 [glide] Add custom strategy for Glide Finance
  src/strategies/glide/examples.json
  src/strategies/glide/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#255 [path-balance-staked-and-locked] add new strategy for holders, stakers and locked tokens to vote
  src/strategies/index.ts
  src/strategies/path-balance-staked-and-locked/README.md
  src/strategies/path-balance-staked-and-locked/examples.json
  src/strategies/path-balance-staked-and-locked/index.ts
  src/strategies/path-balance-staked-and-locked/schema.json
Labels: strategy, ready to merge

#251 [cronaswap] Add strategy for CronaSwap
  src/strategies/cronaswap/README.md
  src/strategies/cronaswap/examples.json
  src/strategies/cronaswap/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#257 [genart] add genart strategy
  src/strategies/genart/examples.json
  src/strategies/genart/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#259 [digitalax-lp-stakers-matic] lp stakers on matic
  src/strategies/digitalax-lp-stakers-matic/examples.json
  src/strategies/digitalax-lp-stakers-matic/index.ts
  src/strategies/digitalax-mona-quickswap/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#252 [squid-dao] Add squid-dao strategy
  src/strategies/index.ts
  src/strategies/squid-dao/README.md
  src/strategies/squid-dao/examples.json
  src/strategies/squid-dao/index.ts
  src/strategies/squid-dao/schema.json
Labels: strategy, ready to merge

#260 [digitalax-mona-stakers-matic] mona staking digitalax
  src/strategies/digitalax-mona-stakers-matic/examples.json
  src/strategies/digitalax-mona-stakers-matic/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#261 [squid-dao] Fix totalScore calculation
  src/strategies/squid-dao/examples.json
  src/strategies/squid-dao/index.ts
Labels: strategy, ready to merge

#254 [orange-reputation-based-voting] add orange-reputation-based-voting
  src/strategies/index.ts
  src/strategies/orange-reputation-based-voting/examples.json
  src/strategies/orange-reputation-based-voting/index.ts
Labels: strategy, ready to merge

#262 [erc721-with-tokenid-weighted] Create erc721-with-tokenid-weighted Strategy
  src/strategies/erc721-with-tokenid-weighted/README.md
  src/strategies/erc721-with-tokenid-weighted/examples.json
  src/strategies/erc721-with-tokenid-weighted/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#267 [math] Add 4 new operations to `math` strategy
  src/strategies/math/README.md
  src/strategies/math/examples.json
  src/strategies/math/index.ts
  src/strategies/math/options.ts
Labels: strategy, ready to merge

#268 [multichain] Support multichain strategy block fetching from custom API
  src/strategies/multichain/README.md
  src/strategies/multichain/index.ts
Labels: strategy, ready to merge

#238 [membership] Add a membership based voting strategy
  README.md
  src/strategies/index.ts
  src/strategies/membership/README.md
  src/strategies/membership/examples.json
  src/strategies/membership/index.ts
Labels: strategy, ready to merge

#275 [contract-call] Support multiple outputs
  src/strategies/contract-call/examples.json
  src/strategies/contract-call/index.ts
Labels: strategy, changes requested
