Repository snapshot-labs/snapshot-strategies, pull requests merged in 2022-04, with the labels that each got.

#518 version 0.0.3 [sd-boost]
  src/strategies/sd-boost/index.ts
Labels: strategy

#519 [reverse-voting-escrow] Fixes Reverse Voting Escrow Scores
  src/strategies/reverse-voting-escrow/examples.json
  src/strategies/reverse-voting-escrow/index.ts
Labels: strategy

#517 [meebitsdao-delegation] Small update to account for lowercase eth addresses + checksums
  src/strategies/meebitsdao-delegation/examples.json
  src/strategies/meebitsdao-delegation/index.ts
Labels: strategy

#521 [erc721-with-metadata] erc721-with-metadata
  src/strategies/erc721-with-metadata/README.md
  src/strategies/erc721-with-metadata/examples.json
  src/strategies/erc721-with-metadata/index.ts
  src/strategies/index.ts
Labels: strategy

#522 [uma-voting] add new strategy uma-voting
  src/strategies/index.ts
  src/strategies/uma-voting/README.md
  src/strategies/uma-voting/examples.json
  src/strategies/uma-voting/index.ts
Labels: strategy

#534 [masterchef-pool-balance-no-rewarddebt] Add masterchef-pool-balance-no-rewarddebt
  src/strategies/index.ts
  src/strategies/masterchef-pool-balance-no-rewarddebt/examples.json
  src/strategies/masterchef-pool-balance-no-rewarddebt/index.ts
Labels: strategy

#532 [proof-of-humanity] Add a new Proof of Humanity strategy
  src/strategies/index.ts
  src/strategies/proof-of-humanity/README.md
  src/strategies/proof-of-humanity/examples.json
  src/strategies/proof-of-humanity/index.ts
  src/strategies/proof-of-humanity/schema.json
Labels: strategy

#527 [cake] add cake pool subgraph
  src/strategies/cake/examples.json
  src/strategies/cake/index.ts
Labels: strategy, changes requested

#529 [squadz-power] Add Squadz-Power Strategy
  src/strategies/index.ts
  src/strategies/squadz-power/README.md
  src/strategies/squadz-power/examples.json
  src/strategies/squadz-power/index.ts
Labels: strategy, changes requested

#547 [orange-reputation-nft-based-voting] update readme
  src/strategies/orange-reputation-nft-based-voting/README.md
Labels: strategy

#538 Fix lint
  src/strategies/conv-finance/index.ts
Labels: ready to merge

#551 [erc1155-all-balances-of] Fix strategy not returning all token balances
  src/strategies/erc1155-all-balances-of/README.md
  src/strategies/erc1155-all-balances-of/examples.json
  src/strategies/erc1155-all-balances-of/index.ts
Labels: strategy

#543 added minto strategy [minto-balance-of-all]
  src/strategies/index.ts
  src/strategies/minto-balance-of-all/README.md
  src/strategies/minto-balance-of-all/examples.json
  src/strategies/minto-balance-of-all/index.ts
  tsconfig.json
Labels: strategy, changes requested

#552 [samurailegends-generals-balance] add generals balance test for samurai legends
  src/strategies/index.ts
  src/strategies/samurailegends-generals-balance/README.md
  src/strategies/samurailegends-generals-balance/examples.json
  src/strategies/samurailegends-generals-balance/index.ts
Labels: strategy, changes requested

#558 version 0.0.2 [stakedao-governance-update]
  src/strategies/index.ts
  src/strategies/stakedao-governance-update/README.md
  src/strategies/stakedao-governance-update/examples.json
  src/strategies/stakedao-governance-update/index.ts
Labels: strategy

#560 [samurailegends-generals-balance] Update strategy with multiplication
  src/strategies/samurailegends-generals-balance/README.md
  src/strategies/samurailegends-generals-balance/examples.json
  src/strategies/samurailegends-generals-balance/index.ts
Labels: strategy

#561 [umami-voting] ADD: mUMAMI Voting Strategy
  src/strategies/index.ts
  src/strategies/sumami-holders/index.ts
  src/strategies/umami-voting/README.md
  src/strategies/umami-voting/examples.json
  src/strategies/umami-voting/index.ts
Labels: strategy

#554 [dogs-unchained] dogs unchained strategy
  src/strategies/dogs-unchained/README.md
  src/strategies/dogs-unchained/examples.json
  src/strategies/dogs-unchained/index.ts
  src/strategies/index.ts
Labels: strategy

#568 [cake] handle subgraph error when block number not sync
  src/strategies/cake/index.ts
Labels: strategy

#570 updated address casing [dogs-unchained]
  src/strategies/dogs-unchained/index.ts
Labels: strategy
