Repository snapshot-labs/snapshot-strategies, pull requests merged in 2022-05, with the labels that each got.

#572 [thresholds] Threshold strategy
  src/strategies/index.ts
  src/strategies/thresholds/README.md
  src/strategies/thresholds/examples.json
  src/strategies/thresholds/index.ts
Labels: strategy, ready to merge

#563 Use yarn in all workflows
  .github/workflows/nodejs.yml
  .github/workflows/publish.yml
  .github/workflows/strategy.yml
Labels: ready to merge

#574 [aavegotchi-agip] support for gotchiLending
  src/strategies/aavegotchi-agip/index.ts
Labels: strategy

#576 [hopr-staking-by-season] Feature/hopr staking s3 s4
  src/strategies/hopr-staking-by-season/examples.json
  src/strategies/hopr-staking-by-season/index.ts
  src/strategies/index.ts
Labels: strategy

#573 Fixed logic issue, pull totalsupply directly [dogs-unchained]
  src/strategies/dogs-unchained/examples.json
  src/strategies/dogs-unchained/index.ts
Labels: strategy

#567 [erc721-with-tokenid-range-weights-simple] Erc721 with tokenid range weights simple v2
  src/strategies/erc721-with-tokenid-range-weights-simple/README.md
  src/strategies/erc721-with-tokenid-range-weights-simple/examples.json
  src/strategies/erc721-with-tokenid-range-weights-simple/index.ts
  src/strategies/erc721-with-tokenid-range-weights-simple/types.d.ts
Labels: strategy

#582 [aavegotchi-agip] fix missing gotchi data with other endpoint
  src/strategies/aavegotchi-agip/index.ts
Labels: strategy

#581 feat: update infinityprotocol-liquidity-pools subgraph query [liquidity-token-provide]
  src/strategies/index.ts
  src/strategies/liquidity-token-provide/README.md
  src/strategies/liquidity-token-provide/examples.json
  src/strategies/liquidity-token-provide/index.ts
Labels: strategy

#586 [meebitsdao-delegation] Get all queries from graphQL query to The Graph, up to 6000 (hosted s…
  src/strategies/meebitsdao-delegation/index.ts
Labels: strategy

#593 [cake] fix subgraph args limit
  src/strategies/cake/index.ts
Labels: strategy

#590 Adds: citydao-square-root 0.0.1 [citydao-square-root]
  src/strategies/citydao-square-root/README.md
  src/strategies/citydao-square-root/examples.json
  src/strategies/citydao-square-root/index.ts
  src/strategies/index.ts
Labels: strategy, changes requested

#587 Erc721 with tokenid range weights simple v2 with fix [erc721-with-tokenid-range-weights-simple]
  src/strategies/erc721-with-tokenid-range-weights-simple/README.md
  src/strategies/erc721-with-tokenid-range-weights-simple/examples.json
  src/strategies/erc721-with-tokenid-range-weights-simple/index.ts
  src/strategies/erc721-with-tokenid-range-weights-simple/types.d.ts
Labels: strategy

#578 New custom strategy [gatenet-total-staked]
  src/strategies/gatenet-total-staked/README.md
  src/strategies/gatenet-total-staked/examples.json
  src/strategies/gatenet-total-staked/index.ts
  src/strategies/gatenet-total-staked/schema.json
  src/strategies/index.ts
Labels: strategy

#594 Use getSnapshots function from snapshot.js [meebitsdao-delegation]
  src/strategies/meebitsdao-delegation/index.ts
  src/strategies/multichain/index.ts
  src/utils.ts
  src/utils/blockfinder.ts
Labels: strategy

#600 Minimum stake policy into strategy [gatenet-total-staked]
  src/strategies/gatenet-total-staked/examples.json
  src/strategies/gatenet-total-staked/index.ts
  src/strategies/gatenet-total-staked/schema.json
Labels: strategy

#602 Add recusal list strategy [recusal-list]
  src/strategies/index.ts
  src/strategies/recusal-list/README.md
  src/strategies/recusal-list/examples.json
  src/strategies/recusal-list/index.ts
  src/strategies/recusal-list/schema.json
Labels: strategy

#588 [gamium-voting] ADDED GAMIUM-VOTING STRATEGY
  src/strategies/gamium-voting/README.md
  src/strategies/gamium-voting/examples.json
  src/strategies/gamium-voting/index.ts
  src/strategies/index.ts
Labels: strategy, changes requested

#608 Make addresses work for checksum addresses [meebitsdao-delegation]
  src/strategies/meebitsdao-delegation/examples.json
  src/strategies/meebitsdao-delegation/index.ts
Labels: strategy

#606 feat: Decentraland Wearable Rarity [decentraland-wearable-rarity]
  src/strategies/decentraland-estate-size/README.md
  src/strategies/decentraland-estate-size/examples.json
  src/strategies/decentraland-estate-size/index.ts
  src/strategies/decentraland-wearable-rarity/README.md
  src/strategies/decentraland-wearable-rarity/examples.json
  src/strategies/decentraland-wearable-rarity/index.ts
  src/strategies/index.ts
Labels: strategy

#610 [aavegotchi-agip] strategy updates for lending
  src/strategies/aavegotchi-agip/index.ts
Labels: strategy

#611 [aavegotchi-agip-17] batch parcel queries
  src/strategies/aavegotchi-agip-17/index.ts
Labels: strategy

#613 [aavegotchi-agip] remove extra loop
  src/strategies/aavegotchi-agip/index.ts
Labels: strategy

#614 Update MMF staking pool [minotaur-money]
  src/strategies/minotaur-money/examples.json
  src/strategies/minotaur-money/index.ts
Labels: strategy

#616 Added the Rowdy Roos voting strategy [rowdy-roos]
  src/strategies/index.ts
  src/strategies/rowdy-roos/README.md
  src/strategies/rowdy-roos/examples.json
  src/strategies/rowdy-roos/index.ts
Labels: strategy, changes requested

#621 Hedgey strategy [hedgey]
  src/strategies/hedgey/README.md
  src/strategies/hedgey/examples.json
  src/strategies/hedgey/index.ts
  src/strategies/index.ts
Labels: strategy
