Repository snapshot-labs/snapshot-strategies, pull requests merged in 2022-01, with the labels that each got.

#276 [erc721-with-tokenid-range-weights] Write strategy for setting weights to erc721 tokenId's by range
  src/strategies/erc721-with-tokenid-range-weights/README.md
  src/strategies/erc721-with-tokenid-range-weights/examples.json
  src/strategies/erc721-with-tokenid-range-weights/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#273 [sumami-holders] Add sUmami holders strategy
  src/strategies/index.ts
  src/strategies/sumami-holders/README.md
  src/strategies/sumami-holders/examples.json
  src/strategies/sumami-holders/index.ts
Labels: strategy, ready to merge

#274 [volt-voting-power] Add strategy for volt holders
  src/strategies/index.ts
  src/strategies/volt-voting-power/README.md
  src/strategies/volt-voting-power/examples.json
  src/strategies/volt-voting-power/index.ts
Labels: strategy, ready to merge

#283 Fix for [volt-voting-power] - change totalStake to match totalTokenSupply
  src/strategies/volt-voting-power/index.ts
Labels: strategy

#282 [erc20-balance-of-indexed] Add erc20-balance-of-indexed strategy
  src/strategies/erc20-balance-of-indexed/README.md
  src/strategies/erc20-balance-of-indexed/examples.json
  src/strategies/erc20-balance-of-indexed/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#291 [digitalax-mona-stakers-matic] Fix conversion of wei to eth
  src/strategies/digitalax-mona-stakers-matic/index.ts
Labels: strategy

#285 [balancer-poolid] snapshot strategy + pagination
  src/strategies/balancer-poolid/README.md
  src/strategies/balancer-poolid/examples.json
  src/strategies/balancer-poolid/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#295 [staked-balancer] snapshot strategy
  src/strategies/index.ts
  src/strategies/staked-balancer/examples.json
  src/strategies/staked-balancer/index.ts
Labels: strategy, ready to merge

#297 adding the bsc and matic delegations
  src/utils/delegation.ts
Labels: ready to merge

#292 [cyberkongz-v2] blacklist
  src/strategies/cyberkongz-v2/examples.json
  src/strategies/cyberkongz-v2/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#300 [saddle-finance-v2] New Snapshot Strategy With Logic Fix
  src/strategies/index.ts
  src/strategies/saddle-finance-v2/README.md
  src/strategies/saddle-finance-v2/examples.json
  src/strategies/saddle-finance-v2/index.ts
  src/strategies/saddle-finance-v2/vestingContractAddrs.ts
Labels: strategy, ready to merge

#290 [aavegotchi-agip-17] new strategy for agip17
  src/strategies/aavegotchi-agip-17/examples.json
  src/strategies/aavegotchi-agip-17/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#301 [erc721-with-tokenid-range-weights-simple] Strategy
  src/strategies/erc721-with-tokenid-range-weights-simple/README.md
  src/strategies/erc721-with-tokenid-range-weights-simple/examples.json
  src/strategies/erc721-with-tokenid-range-weights-simple/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#294 [aavegotchi] newer staking pool power
  src/strategies/aavegotchi/examples.json
  src/strategies/aavegotchi/index.ts
Labels: strategy, ready to merge

#302 [galaxy-nft-with-score] Add matic support and switch subgraphs
  src/strategies/galaxy-nft-with-score/examples.json
  src/strategies/galaxy-nft-with-score/index.ts
Labels: strategy, ready to merge

#307 [genomesdao] feat: strategy for genomesdao
  src/strategies/genomesdao/README.md
  src/strategies/genomesdao/examples.json
  src/strategies/genomesdao/index.ts
  src/strategies/genomesdao/schema.json
  src/strategies/index.ts
Labels: strategy, ready to merge

#308 Test case to check schema (if available) is valid with example.json
  test/index.spec.ts
Labels: ready to merge

#298 convert npm to yarn lock file and update readme
  .github/workflows/main.yml
  README.md
  package-lock.json
  yarn.lock
Labels: ready to merge

#305 [staked-uniswap-modifiable] strategy to allow modification of method ABI to get balance in uniswap LP staking contract
  src/strategies/index.ts
  src/strategies/staked-uniswap-modifiable/README.md
  src/strategies/staked-uniswap-modifiable/examples.json
  src/strategies/staked-uniswap-modifiable/index.ts
Labels: strategy, ready to merge

#310 [aavegotchi-agip-17] Update index.ts
  src/strategies/aavegotchi-agip-17/index.ts
  src/strategies/aavegotchi-agip/index.ts
Labels: strategy

#314 [digitalax-deco-to-mona] new strategy
  src/strategies/digitalax-deco-to-mona/README.md
  src/strategies/digitalax-deco-to-mona/examples.json
  src/strategies/digitalax-deco-to-mona/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#313 [total-axion-shares] Update total-axion-shares strategy
  src/strategies/total-axion-shares/examples.json
  src/strategies/total-axion-shares/index.ts
Labels: strategy, ready to merge

#326 [genomesdao]: Strategy for genomesdao
  src/strategies/genomesdao/index.ts
Labels: strategy, ready to merge

#317 [giveth-xdai-balance] added two new strategies for GIveth
  src/strategies/giveth-balancer-balance/README.md
  src/strategies/giveth-balancer-balance/examples.json
  src/strategies/giveth-balancer-balance/index.ts
  src/strategies/giveth-xdai-balance/README.md
  src/strategies/giveth-xdai-balance/examples.json
  src/strategies/giveth-xdai-balance/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#324 [sandman-dao] Adds SandmanDAO strategy
  src/strategies/index.ts
  src/strategies/sandman-dao/README.md
  src/strategies/sandman-dao/examples.json
  src/strategies/sandman-dao/index.ts
Labels: strategy, ready to merge

#329 [xkawa-farm] fix: update strategy xKawa-farm
  src/strategies/xkawa-farm/examples.json
  src/strategies/xkawa-farm/index.ts
Labels: strategy, ready to merge

#331 [erc1155-balance-of-ids] Fixed erc1155-balance-of-ids and erc1155-balance-of-ids-weighted strategies
  src/strategies/erc1155-balance-of-ids-weighted/examples.json
  src/strategies/erc1155-balance-of-ids/examples.json
  src/strategies/erc1155-balance-of-ids/index.ts
Labels: strategy, ready to merge

#334 [spacey2025] Add spacey2025 strategy
  src/strategies/index.ts
  src/strategies/spacey2025/README.md
  src/strategies/spacey2025/examples.json
  src/strategies/spacey2025/index.ts
Labels: strategy, ready to merge

#328 [immutable-x] Add Immutable X strategy
  src/strategies/immutable-x/examples.json
  src/strategies/immutable-x/index.ts
  src/strategies/index.ts
Labels: strategy, ready to merge

#336 [delegation] Allow delegation strategy to accept space name from strategy params
  src/strategies/delegation/README.md
  src/strategies/delegation/index.ts
Labels: strategy, ready to merge

#338 Delegation subgraph for gnosis chain
  src/utils/delegation.ts
Labels: ready to merge

#330 [sushiswap] Add masterchef v2 stakedLP + all sushi chains
  src/strategies/sushiswap/README.md
  src/strategies/sushiswap/examples.json
  src/strategies/sushiswap/index.ts
Labels: strategy

#335 Adds Banksy Farm DAO strategy [banksy-dao]
  src/strategies/banksy-dao/README.md
  src/strategies/banksy-dao/examples.json
  src/strategies/banksy-dao/index.ts
  src/strategies/index.ts
Labels: strategy

#340 [stakers-and-holders] Add new strategy
  src/strategies/index.ts
  src/strategies/stakers-and-holders/README.md
  src/strategies/stakers-and-holders/examples.json
  src/strategies/stakers-and-holders/index.ts
Labels: strategy

#348 [ve-balance-of-at] Add ve-balance-of-at strategy
  src/strategies/index.ts
  src/strategies/ve-balance-of-at/README.md
  src/strategies/ve-balance-of-at/examples.json
  src/strategies/ve-balance-of-at/index.ts
  src/strategies/ve-balance-of-at/schema.json
Labels: strategy

#344 [multichain] Use blockfinder to get block nums
  src/strategies/multichain/examples.json
  src/strategies/multichain/index.ts
Labels: strategy
