Repository snapshot-labs/snapshot-strategies, pull requests merged in 2022-02, with the labels that each got.

#349 [staked-daomaker] Adding DAOMaker Staking Strategy for voting
  src/strategies/index.ts
  src/strategies/staked-daomaker/README.md
  src/strategies/staked-daomaker/examples.json
  src/strategies/staked-daomaker/index.ts
Labels: strategy, changes requested

#359 [landdao-token-tiers] restrict fetch to IPFS
  src/strategies/index.ts
  src/strategies/landdao-token-tiers/README.md
  src/strategies/landdao-token-tiers/examples.json
  src/strategies/landdao-token-tiers/index.ts
Labels: strategy

#354 [revest] Created Revest Staking System strategy
  src/strategies/index.ts
  src/strategies/revest/examples.json
  src/strategies/revest/index.ts
Labels: strategy, changes requested

#355 [erc20-balance-of-delegation] Add delegation space param
  src/strategies/erc20-balance-of-delegation/examples.json
  src/strategies/erc20-balance-of-delegation/index.ts
Labels: strategy, ready to merge

#357 [chubbykaijudao] ChubbyKaijuDAO staker-and-holder strategy
  src/strategies/chubbykaijudao/README.md
  src/strategies/chubbykaijudao/examples.json
  src/strategies/chubbykaijudao/index.ts
  src/strategies/index.ts
Labels: strategy

#358 Use typeof for latest block query param in snapshot strategy [immutable-x]
  src/strategies/immutable-x/index.ts
Labels: strategy

#352 [razor-network-voting] Razor Network Voting Strategy
  src/index.ts
  src/strategies/index.ts
  src/strategies/razor-network-voting/examples.json
  src/strategies/razor-network-voting/index.ts
Labels: strategy, changes requested

#365 [multichain] Ignore space network from blocks in multichain
  src/strategies/multichain/index.ts
Labels: strategy

#372 [defiplaza] feat: new DefiPlaza strategy
  src/strategies/defiplaza/README.md
  src/strategies/defiplaza/examples.json
  src/strategies/defiplaza/index.ts
  src/strategies/defiplaza/schema.json
  src/strategies/index.ts
Labels: strategy

#306 [ocean-dao-brightid] Update `ocean-dao-brightid` strategy
  src/strategies/ocean-dao-brightid/README.md
  src/strategies/ocean-dao-brightid/examples.json
  src/strategies/ocean-dao-brightid/index.ts
Labels: strategy, ready to merge

#342 [ethercats-founder-series] added ethercats nft strategy
  src/strategies/ethercats-founder-series/examples.json
  src/strategies/ethercats-founder-series/index.ts
  src/strategies/index.ts
Labels: strategy, changes requested

#378 [razor-network-voting] Razor Network Voting
  src/strategies/razor-network-voting/examples.json
  src/strategies/razor-network-voting/index.ts
Labels: strategy

#386 [staking-claimed-unclaimed] adding staking-claimed-unclaimed strategy
  src/strategies/index.ts
  src/strategies/staking-claimed-unclaimed/README.md
  src/strategies/staking-claimed-unclaimed/examples.json
  src/strategies/staking-claimed-unclaimed/index.ts
Labels: strategy

#389 Send slices of addresses base on page size in imx strategy [immutable-x]
  src/strategies/immutable-x/index.ts
Labels: strategy

#390 [erc20-balance-of] Add more validation to ERC20 strategy schema
  src/strategies/erc20-balance-of/schema.json
Labels: strategy

#391 [erc721] Add more validation to ERC721 strategy schema
  src/strategies/erc721/schema.json
Labels: strategy

#387 [galaxy-nft-with-score] Change the way of querying subgraph to fix scaling issue
  src/strategies/galaxy-nft-with-score/examples.json
  src/strategies/galaxy-nft-with-score/index.ts
Labels: strategy

#394 [printer-financial] added strategy for printer financial contracts
  src/strategies/index.ts
  src/strategies/printer-financial/examples.json
  src/strategies/printer-financial/index.ts
  src/strategies/printer-financial/schema.json
Labels: strategy

#400 [ocean-dao-brightid] Add `Math.sqrt` to ocean-dao-brightid strategy
  src/strategies/ocean-dao-brightid/index.ts
Labels: strategy

#401 [printer-financial] add pool id to printer-financial strategy
  src/strategies/printer-financial/examples.json
  src/strategies/printer-financial/index.ts
  src/strategies/printer-financial/schema.json
Labels: strategy

#396 [starsharks] add strategy for starsharks voting
  src/strategies/index.ts
  src/strategies/starsharks/README.md
  src/strategies/starsharks/examples.json
  src/strategies/starsharks/index.ts
Labels: strategy, changes requested

#405 Added EtherCats Founders Series NFT strategy [ethercats-founders-series]
  src/strategies/ethercats-founders-series/examples.json
  src/strategies/ethercats-founders-series/index.ts
  src/strategies/index.ts
Labels: strategy

#410 Fix imx strategy slice logic [immutable-x]
  src/strategies/immutable-x/examples.json
  src/strategies/immutable-x/index.ts
Labels: strategy

#411 [ocean-dao-brightid] Remove the square root
  src/strategies/ocean-dao-brightid/index.ts
Labels: strategy

#407 [minotaur-money] Add minotaur-money strategy
  src/strategies/index.ts
  src/strategies/minotaur-money/examples.json
  src/strategies/minotaur-money/index.ts
Labels: strategy, changes requested

#414 [immutable-x] Add support for requests without addresses in json body for imx strategy
  src/strategies/immutable-x/index.ts
Labels: strategy

#319 [brightid] Revising the BrightID Strategy
  src/strategies/brightid/README.md
  src/strategies/brightid/examples.json
  src/strategies/brightid/index.ts
Labels: strategy

#413 [safety-module-bpt-power] Add safety module bpt strategy
  src/strategies/index.ts
  src/strategies/safety-module-bpt-power/README.md
  src/strategies/safety-module-bpt-power/examples.json
  src/strategies/safety-module-bpt-power/index.ts
  src/strategies/safety-module-bpt-power/schema.json
Labels: strategy

#419 [protofi-erc721-tier-weighted] Protofi nft strategy
  src/strategies/index.ts
  src/strategies/protofi-erc721-tier-weighted/README.md
  src/strategies/protofi-erc721-tier-weighted/examples.json
  src/strategies/protofi-erc721-tier-weighted/index.ts
Labels: strategy
