Repository snapshot-labs/snapshot-strategies, pull requests merged in 2022-03, with the labels that each got.

#428 Add orange-reputation-nft-based-voting strategy [orange-reputation-nft-based-voting]
  src/strategies/index.ts
  src/strategies/orange-reputation-nft-based-voting/README.md
  src/strategies/orange-reputation-nft-based-voting/examples.json
  src/strategies/orange-reputation-nft-based-voting/index.ts
Labels: strategy, changes requested

#429 [erc721-multi-registry-weighted] Add FRWC token weighted strategy
  src/strategies/erc721-multi-registry-weighted/README.md
  src/strategies/erc721-multi-registry-weighted/examples.json
  src/strategies/erc721-multi-registry-weighted/index.ts
  src/strategies/index.ts
Labels: strategy, changes requested

#432 [ocean-marketplace] Add other networks for ocean-marketplace strategy
  src/strategies/ocean-marketplace/index.ts
Labels: strategy

#434 [minotaur-money] Makes the voting units absolute MINO held instead of % of MINO supply.
  src/strategies/minotaur-money/examples.json
  src/strategies/minotaur-money/index.ts
Labels: strategy

#433 [ve-ribbon] New strategy ve-ribbon
  src/strategies/index.ts
  src/strategies/ve-ribbon/README.md
  src/strategies/ve-ribbon/examples.json
  src/strategies/ve-ribbon/index.ts
  src/strategies/ve-ribbon/schema.json
Labels: strategy, changes requested

#441 [wanakafarm-staking] Add strategies wanakafarm staking
  src/strategies/index.ts
  src/strategies/wanakafarm-staking/examples.json
  src/strategies/wanakafarm-staking/index.ts
Labels: strategy

#437 [swapr] fix: update Swapr Arbitrum One subgraph endpoint
  src/strategies/swapr/commons.ts
Labels: strategy

#452 [sd-boost] sd-boost initial implementation
  src/strategies/index.ts
  src/strategies/sd-boost/README.md
  src/strategies/sd-boost/examples.json
  src/strategies/sd-boost/index.ts
Labels: strategy, changes requested

#456 [ve-ribbon-voting-power] verbn voting
  src/strategies/index.ts
  src/strategies/ve-ribbon-voting-power/README.md
  src/strategies/ve-ribbon-voting-power/examples.json
  src/strategies/ve-ribbon-voting-power/index.ts
  src/strategies/ve-ribbon-voting-power/schema.json
Labels: strategy

#465 [oolongswap] create strategy
  src/strategies/index.ts
  src/strategies/oolongswap/examples.json
  src/strategies/oolongswap/index.ts
Labels: strategy

#469 [wanakafarm-land-ingame] Add strategies wanakafarm land ingame
  src/strategies/index.ts
  src/strategies/wanakafarm-land-ingame/examples.json
  src/strategies/wanakafarm-land-ingame/index.ts
Labels: strategy

#468 [erc20-rebase-wrapper] erc20-rebase-wrapper strategy
  src/strategies/erc20-rebase-wrapper/README.md
  src/strategies/erc20-rebase-wrapper/examples.json
  src/strategies/erc20-rebase-wrapper/index.ts
  src/strategies/index.ts
Labels: strategy

#464 [meebitsdao-delegation] New MeebitsDAO voting strategy
  src/strategies/index.ts
  src/strategies/meebitsdao-delegation/README.md
  src/strategies/meebitsdao-delegation/examples.json
  src/strategies/meebitsdao-delegation/index.ts
Labels: strategy

#460 [ocean-dao-brightid] Delegation support
  src/strategies/ocean-dao-brightid/examples.json
  src/strategies/ocean-dao-brightid/index.ts
Labels: strategy, changes requested

#461 [hopr-staking-s2] Hopr staking v2
  src/strategies/hopr-staking-s2/examples.json
  src/strategies/hopr-staking-s2/index.ts
  src/strategies/index.ts
Labels: strategy

#463 [erc20-votes-with-override] Adding compatibility for Snapshot delegations.
  src/strategies/erc20-votes-with-override/README.md
  src/strategies/erc20-votes-with-override/index.ts
Labels: strategy

#472 [capitaldao-staking] Capital Dao Staking Token
  src/strategies/capitaldao-staking/README.md
  src/strategies/capitaldao-staking/examples.json
  src/strategies/capitaldao-staking/index.ts
  src/strategies/index.ts
Labels: strategy

#457 [planet-finance-v2] Planet V2 voting strategy
  src/strategies/index.ts
  src/strategies/planet-finance-v2/examples.json
  src/strategies/planet-finance-v2/index.ts
Labels: strategy, changes requested

#459 [conv-finance] Adding new strategy for LP token, staking pool and reward calculation
  src/strategies/conv-finance/examples.json
  src/strategies/conv-finance/index.ts
  src/strategies/index.ts
Labels: strategy, changes requested

#476 Remove try catch on cake and reduce timeout to 15 seconds as there is one per address
  src/strategies/cake/index.ts
  src/utils.ts
Labels: ready to merge

#467 [gno] GNO voting strategy
  src/strategies/gno/examples.json
  src/strategies/gno/index.ts
  src/strategies/index.ts
Labels: strategy, changes requested

#483 [galaxy-nft-with-score] fix only 100 NFTs shows under certain contract by default
  src/strategies/galaxy-nft-with-score/examples.json
  src/strategies/galaxy-nft-with-score/index.ts
Labels: strategy

#489 [cake] fix cake
  src/strategies/cake/examples.json
  src/strategies/cake/index.ts
Labels: strategy

#486 [math] Add a new math method: multiply.
  src/strategies/math/README.md
  src/strategies/math/examples.json
  src/strategies/math/index.ts
  src/strategies/math/options.ts
Labels: strategy, changes requested

#493 Aelin council strategy updated [aelin-council]
  src/strategies/aelin-council/examples.json
  src/strategies/aelin-council/index.ts
Labels: strategy, changes requested

#495 [ocean-dao-brightid] Fix NaN scores
  src/strategies/ocean-dao-brightid/index.ts
Labels: strategy

#492 [goldfinch-membership] goldfinch-membership strategy
  src/strategies/goldfinch-membership/examples.json
  src/strategies/goldfinch-membership/index.ts
  src/strategies/index.ts
Labels: strategy, changes requested

#497 [goldfinch-voting-power] Implement goldfinch voting power strategy
  src/strategies/goldfinch-voting-power/examples.json
  src/strategies/goldfinch-voting-power/index.ts
  src/strategies/index.ts
Labels: strategy

#502 [synthetix_1] Update Synthetix Strategy
  src/strategies/index.ts
  src/strategies/synthetix_1/README.md
  src/strategies/synthetix_1/examples.json
  src/strategies/synthetix_1/index.ts
Labels: strategy

#482 [genomesdao] fix: add veGNOME to calculate the power of voting
  src/strategies/genomesdao/README.md
  src/strategies/genomesdao/examples.json
  src/strategies/genomesdao/index.ts
  src/strategies/genomesdao/schema.json
Labels: strategy, changes requested

#504 [gno] Remove subgraph network on GNO strategy
  src/strategies/gno/examples.json
  src/strategies/gno/index.ts
Labels: strategy

#505 [gno] fix user id case
  src/strategies/gno/examples.json
  src/strategies/gno/index.ts
Labels: strategy

#508 [thales] Change Thales strategy to pull data from OP mainnet
  src/strategies/thales/examples.json
  src/strategies/thales/index.ts
Labels: strategy, changes requested

#466 delegationSpace param to delegate strategy examples.json
  src/strategies/delegation/examples.json
Labels: ready to merge

#515 [reverse-voting-escrow] Reverse Voting Escrow Strategy
  src/strategies/index.ts
  src/strategies/reverse-voting-escrow/README.md
  src/strategies/reverse-voting-escrow/examples.json
  src/strategies/reverse-voting-escrow/index.ts
  test/scores.ts
Labels: strategy
