Repository snapshot-labs/snapshot-strategies, pull requests merged in 2022-08, with the labels that each got.

#754 Update subgraph address for uniswap quickswap code [digitalax-mona-quickswap]
  src/strategies/digitalax-mona-quickswap/index.ts
Labels: strategy

#740 added flexible voucher strategies [erc3525-flexible-voucher]
  src/strategies/erc3525-flexible-voucher/examples.json
  src/strategies/erc3525-flexible-voucher/index.ts
  src/strategies/erc3525-flexible-voucher/utils.ts
  src/strategies/index.ts
Labels: strategy

#753 new strategy: decaying voting power for staked ERC 1155s [echelon-cached-erc1155-decay]
  src/strategies/echelon-cached-erc1155-decay/README.md
  src/strategies/echelon-cached-erc1155-decay/examples.json
  src/strategies/echelon-cached-erc1155-decay/index.ts
  src/strategies/index.ts
Labels: strategy

#758 erc3525 vesting voucher change amount take value [erc3525-vesting-voucher]
  src/strategies/erc3525-vesting-voucher/index.ts
Labels: strategy

#757 feat: add harmony-staking strategy [harmony-staking]
  src/strategies/harmony-staking/examples.json
  src/strategies/harmony-staking/index.ts
  src/strategies/index.ts
Labels: strategy

#755 feat: prepo vesting contract weighted voting [prepo-vesting]
  src/strategies/index.ts
  src/strategies/prepo-vesting/README.md
  src/strategies/prepo-vesting/examples.json
  src/strategies/prepo-vesting/index.ts
  src/strategies/prepo-vesting/schema.json
Labels: strategy

#748 feat: add a strategy to calc blance with subgraph [balance-of-subgraph]
  src/strategies/balance-of-subgraph/README.md
  src/strategies/balance-of-subgraph/examples.json
  src/strategies/balance-of-subgraph/index.ts
  src/strategies/index.ts
Labels: strategy

#777 feat: Add vlAURA to veBAL balanceOf strategy [aura-balance-of-vlaura-vebal]
  src/strategies/aura-balance-of-vlaura-vebal/README.md
  src/strategies/aura-balance-of-vlaura-vebal/examples.json
  src/strategies/aura-balance-of-vlaura-vebal/index.ts
  src/strategies/aura-balance-of-vlaura-vebal/schema.json
  src/strategies/index.ts
Labels: strategy

#774 Proxy Protocol ERC1155 [proxyprotocol-erc1155-balance-of]
  src/strategies/index.ts
  src/strategies/proxyprotocol-erc1155-balance-of/README.md
  src/strategies/proxyprotocol-erc1155-balance-of/examples.json
  src/strategies/proxyprotocol-erc1155-balance-of/index.ts
Labels: strategy, changes requested

#775 Proxy Protocol ERC721 [proxyprotocol-erc721-balance-of]
  src/strategies/index.ts
  src/strategies/proxyprotocol-erc721-balance-of/README.md
  src/strategies/proxyprotocol-erc721-balance-of/examples.json
  src/strategies/proxyprotocol-erc721-balance-of/index.ts
  src/strategies/proxyprotocol-erc721-balance-of/schema.json
Labels: strategy, changes requested

#776 Proxy Protocol ERC20 [proxyprotocol-erc20-balance-of]
  src/strategies/index.ts
  src/strategies/proxyprotocol-erc20-balance-of/README.md
  src/strategies/proxyprotocol-erc20-balance-of/examples.json
  src/strategies/proxyprotocol-erc20-balance-of/index.ts
  src/strategies/proxyprotocol-erc20-balance-of/schema.json
Labels: strategy, changes requested

#683 [gooddollar-multichain] New strategy
  src/strategies/gooddollar-multichain/README.md
  src/strategies/gooddollar-multichain/examples.json
  src/strategies/gooddollar-multichain/index.ts
  src/strategies/index.ts
Labels: strategy, changes requested

#770 [orca-pod] Orca pods strategy
  src/strategies/index.ts
  src/strategies/orca-pod/README.md
  src/strategies/orca-pod/examples.json
  src/strategies/orca-pod/index.ts
  src/strategies/orca-pod/schema.json
Labels: strategy, ready to merge

#784 Add vesting contract strategy [arrow-vesting]
  src/strategies/arrow-vesting/README.md
  src/strategies/arrow-vesting/examples.json
  src/strategies/arrow-vesting/index.ts
  src/strategies/index.ts
Labels: strategy

#787 Feat/update strategy [prepo-vesting]
  src/strategies/prepo-vesting/README.md
  src/strategies/prepo-vesting/index.ts
Labels: strategy

#788 Tutellus DAO protocol strategy [tutellus-protocol]
  src/strategies/index.ts
  src/strategies/tutellus-protocol/README.md
  src/strategies/tutellus-protocol/examples.json
  src/strategies/tutellus-protocol/index.ts
  src/strategies/tutellus-protocol/schema.json
Labels: strategy

#782 Add fight-club strategy [fight-club]
  src/strategies/fight-club/README.md
  src/strategies/fight-club/examples.json
  src/strategies/fight-club/index.ts
  src/strategies/index.ts
Labels: strategy

#790 [orbs-network-delegation] fix address sanitation
  src/strategies/orbs-network-delegation/examples.json
  src/strategies/orbs-network-delegation/index.ts
Labels: strategy

#792 Disambiguate "voting weight" and "weight class" [fight-club]
  src/strategies/fight-club/README.md
Labels: strategy

#798 tpro-staking v1.0.0 [tpro-staking]
  src/strategies/index.ts
  src/strategies/tpro-staking/examples.json
  src/strategies/tpro-staking/index.ts
Labels: strategy

#799 [gysr-pending-rewards] Add gysr-pending-rewards strategy
  src/strategies/gysr-pending-rewards/README.md
  src/strategies/gysr-pending-rewards/examples.json
  src/strategies/gysr-pending-rewards/index.ts
  src/strategies/gysr-pending-rewards/schema.json
  src/strategies/index.ts
Labels: strategy

#802 [harmony-staking] add testnet example
  src/strategies/harmony-staking/examples.json
Labels: strategy

#807 [gysr-lp-staking-balance] Add GYSR Strategy
  src/strategies/gysr-lp-staking-balance/README.md
  src/strategies/gysr-lp-staking-balance/examples.json
  src/strategies/gysr-lp-staking-balance/index.ts
  src/strategies/gysr-lp-staking-balance/schema.json
  src/strategies/index.ts
Labels: strategy

#801 [safe-vested] Add safe vested strategy
  src/strategies/index.ts
  src/strategies/safe-vested/README.md
  src/strategies/safe-vested/examples.json
  src/strategies/safe-vested/index.ts
Labels: strategy

#809 [gysr-pending-rewards] Change example
  src/strategies/gysr-pending-rewards/examples.json
Labels: strategy
